name = "AttractorNetworksTests"
uuid = "677e1249-efd0-4ff5-b55b-9733b999eb6e"
authors = ["Dylan Festa"]
version = "0.1.0"

[deps]
AttractorNetworksBase = "32aebfaa-1084-4881-a576-9addc3705ed5"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
